### Atualiza os dados de uma animal
PUT
http://localhost:8080/animals/5ec3ddb374534961902e1aed
@Content-Type: application/json
{
    "specie": "Leão",
    "name": "Bingo King",
    "gender": "F",
    "age": 5
}

%%%

# Duration: 70 ms
# URL: http://localhost:8080/animals/5ec3ddb374534961902e1aed

# HTTP/1.1 200

@Content-Type: application/json
@Transfer-Encoding: chunked
@Date: Tue, 19 May 2020 13:24:11 GMT
@Keep-Alive: timeout=60
@Connection: keep-alive

{
  "id": "5ec3ddb374534961902e1aed",
  "specie": "Leão",
  "name": "Bingo King",
  "gender": "M",
  "age": 5
}